//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AISTaskDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.ItemPackage = new HashSet<ItemPackage>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> LastSalePrice { get; set; }
        public Nullable<decimal> LastPurchasePrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<int> StorID { get; set; }
        public Nullable<bool> UnitType { get; set; }
    
        public virtual Stor Stor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPackage> ItemPackage { get; set; }
    }
}
