//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AISTaskDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPackage
    {
        public int ID { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> PackageID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Package Package { get; set; }
    }
}
